# https://github.com/apache/infrastructure-asfyaml/blob/main/README.md

notifications:
  issues: notifications@community.apache.org

github:
  homepage: https://community.apache.org/
  features:
    issues: true
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
