name: Metrics

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      cache-name: data-cache-metrics
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true

      - name: Fetch cache data
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
        with:
          key: ${{ env.cache-name }}
          path: site/data

      - name: Install dependencies
        run: uv sync --all-groups

      - name: build # initial limited test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -lR site # before
          cp config.example.yml config.yml
          uv run asfmetrics --project attic # initial limited test
          ls -lR site # after
          # Check if there is a cache entry before trying to delete
          # This ensure delete failures cause the build to fail
          if [ -n "$(gh cache list -k ${{ env.cache-name }} --json id --jq '.[].id')" ]
          then
            echo "Removing cache"
            gh cache delete ${{ env.cache-name }}
          else
            echo "No cache found"
          fi


      - name: Update cache data
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
        with:
          key: ${{ env.cache-name }}
          path: site/data

      - name: Upload generated output - debug
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: generated-site
          path: site
          retention-days: 14

